<?xml version="1.0" standalone="yes"?>
<!DOCTYPE employees [
<!ELEMENT employees (employee)>
<!ELEMENT employee (name,Gender,Phone,MailId,Address,workexerience)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT Gender (#PCDATA)>
<!ELEMENT Phone (#PCDATA) >
<!ELEMENT MailId (#PCDATA) >
<!ELEMENT Address (#PCDATA) >
<!ELEMENT workexerience (#PCDATA)>
]>
<employees type="web">
  <employee>
    <name>Sarika Jha</name>
    <Gender>Female</Gender>
	<Phone>9686677521</Phone>
	<MailId>agfhncwds@gmail.com</MailId>
	<Address>Nelamangala</Address>
	<workexerience>1</workexerience>
  </employee>
  <employee>
    <name>Anju Jha</name>
    <Gender>Female</Gender>
	<Phone>9685477521</Phone>
	<MailId>dfge87@gmail.com</MailId>
	<Address>HSR</Address>
	<workexerience>16</workexerience>
  </employee>
</employees>